### ISSUE TITLE
Lamda Ex. Sorunu

### ISSUE THREAD

**Issue by emrecemaksu** [emrecemaksu/UnitTest#2]
https://github.com/emrecemaksu/UnitTest/blob/9b46900a9458a8cb1f16eb46025991e74f7a5f97/source-code-starter-1/source-code-starter/TestNinja/TestNinja.UnitTests/ErrorLoggerTests.cs#L33

Burada normalde parametre () alması gereken yer neden boş kaldı?
Lambda expression kullanılmadığında "void ögesinden System.action ögesine dönüştürülemiyor." hatası alınıyor.
Boş bıraktığımız zaman Assert.ThrowsException ın istediği parametreyi kendisinin belirlemesini mi sağlıyoruz?
Eğer boş kalmasaydı () içine ne gelebilirdi?

**Comment by gokhangulbiz** [comment]
Çok kısa özet: bu arkadaşları wrap edilmiş delegate olarak düşünebilirsin. Delegate ne? Bir method un pointer'ı. Eğer bu method birşey dönmüyorsa (yani dönüş tipi void ise) Action, dönüş tipi varsa Func diye tanımlanıyor.

Action ve Func arasındaki farkı araştırman seni çözüme götürecektir. Aşağıdaki linkte sol taraftaki navigasyonda Action'dan inherit etmiş bir sürü generic class göreceksin. Aralarındaki farka bir bak :)

https://docs.microsoft.com/en-us/dotnet/api/system.action?view=netframework-4.7.2

Aynı durum Func için de geçerli,

https://docs.microsoft.com/en-us/dotnet/api/system.func-1?view=netframework-4.7.2

**Comment by emrecemaksu** [comment]
https://github.com/emrecemaksu/UnitTest/blob/dd24b6c12323ffe1c65fb74c79390b1edaf77402/source-code-starter-1/source-code-starter/TestNinja/TestNinja.UnitTests/DemeritPointsCalculatorTets.cs#L14

https://github.com/emrecemaksu/UnitTest/blob/dd24b6c12323ffe1c65fb74c79390b1edaf77402/source-code-starter-1/source-code-starter/TestNinja/TestNinja_NUnitTest/ErrorLoggerTests_NUnit.cs#L19

Ms Unit Test ve N Unit Testte ThrowsException olaylarını incelerken kullanımı Lambda expression ile birlikte bu şekilde olması gerekmekte. Sebebi ThrowsException'ın `public static T ThrowsException<T>(Func<object> action) where T : Exception;` metasında da görüldüğü gibi oluşan Action'un Func olarak tanıtılması istenmesi. @gokhangulbiz
