### ISSUE TITLE
Delegate Ve Event

### ISSUE THREAD

**Issue by emrecemaksu** [emrecemaksu/UnitTest#3]
https://github.com/emrecemaksu/UnitTest/blob/9b46900a9458a8cb1f16eb46025991e74f7a5f97/source-code-starter-1/source-code-starter/TestNinja/TestNinja_NUnitTest/ErrorLoggerTests_NUnit.cs#L29

id = 00...000 olarak geçerken. 29. satırdan sonra nasıl geriye dönük farklı değer aldı.
id olay gerçekleşse bile local bir değişken değil mi?
b nasıl id ye etki etti bunu sağlayan event olayı mı?

**Comment by gokhangulbiz** [comment]
https://github.com/emrecemaksu/UnitTest/blob/9b46900a9458a8cb1f16eb46025991e74f7a5f97/source-code-starter-1/source-code-starter/TestNinja/TestNinja/Fundamentals/ErrorLogger.cs#L12-L24

21. satırdaki yorumunu anlamadım. Eventhandler üzerinde bir method çağırıyorsun. Dinamik birşey yok burada.

22. satırdaki yorum için "null propagation" ı araştırmalısın.

23. satırda için ise, logger.Log(....) çağırdığında, ErrorLogged diye event raise oluyor ve ikinci parametresinde random guid paslıyor. Test kodunda da localde empty guid tutuyorsun, ve ErrorLogged eventinden gelen yeni Id yi bunun üzerine yazıyorsun. Ve sonra da test ediyorsun bu yeni Id empty guid dan farklı mı diye.
